name: lh-tactics
version: 0.1.0.28
github: "dannymf/lh-tactics"
license: BSD3
author: "Daniel Friedman"
maintainer: "df19@princeton.edu"
copyright: "Daniel Friedman 2024"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at
  <https://github.com/githubuser/lh-tactics#readme>

dependencies:
  - liquidhaskell == 0.8.10.7
  - liquid-base == 4.15.0.0
  - template-haskell == 2.17.0.0
  # - template-haskell == 2.16.0.0 # causes build error
  - parsec
  - haskell-src-meta
  - th-abstraction
  - containers
  - mtl
  - transformers
  - process
  - strict-io

library:
  source-dirs: src
  # ghc-options:
  #   - -fplugin=LiquidHaskell
  # - -fplugin-opt=LiquidHaskell:--reflection
  # - -fplugin-opt=LiquidHaskell:--ple-local
  # - -ddump-splices

executable:
  main: Main.hs
  source-dirs:
    - app
    - src
  # ghc-options:
  #   - -fplugin=LiquidHaskell
  # - -fplugin-opt=LiquidHaskell:--reflection
  # - -fplugin-opt=LiquidHaskell:--ple-local
  # - -ddump-splices
  # build-depends:
  #   - lh-tactics # for some reason, also have to add to lh-tactics.cabal even though it will automatically get removed...

tests:
  test-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -ddump-splices
    dependencies:
      - lh-tactics
